name: JFrog CI testing for Fedora

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install HAProxy 2.2.
      uses: timwolla/action-install-haproxy@main
      id: install-haproxy
      with:
        branch: "2.2"
        use_openssl: yes

    - name: Install Ansible
      run: |
        python3 -m pip install ansible
        # ls -lath . #cat .generated/jfrog.fcc | yq '.storage.files[5]'

    - name: Install needed pip modules
      run: |
        python3 --version
        python3 -m pip install -r ./requirements.txt

    - name: Install needed Ansible Collections
      run: |
        ansible-galaxy collection install -r ./collections/requirements.yml

    - name: Genereate ssl cert
      run: | 
        openssl req -newkey rsa:2048 -nodes -keyout /tmp/self-signed.key -x509 -days 365 -out /tmp/self-signed.crt -subj "/CN=localhost"

        # Verify certificate
        openssl x509 -noout -text -in /tmp/self-signed.crt

        # Print paths of generated files
        echo "Certificate: /tmp/self-signed.crt"
        echo "Key: /tmp/self-signed.key"
    - name: Deploy JFrog to FCOS Testing
      run: |
        cp example.vars.yml vars.yml
        echo "Certificate: /tmp/self-signed.crt"
        echo "Key: /tmp/self-signed.key"
        ansible-playbook -e "@vars.yml" 1_bootstrap.yml -t create_ignition_file
        ls -lath -R  ./.generated
