name: JFrog CI testing for Fedora

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Test code
      run: |
        ls -lath . #cat .generated/jfrog.fcc | yq '.storage.files[5]'  